// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsM7qeT1vdZrThHozZpI5Faq1ivj-jKPg',
    appId: '1:974045621368:web:c889fc6ef0bcc3fb23d18d',
    messagingSenderId: '974045621368',
    projectId: 'flavr-4e17f',
    authDomain: 'flavr-4e17f.firebaseapp.com',
    storageBucket: 'flavr-4e17f.firebasestorage.app',
    measurementId: 'G-5Y1XDRKBRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOC0aMx6NR53p2rj5JbKByTNgLgEVMC2Q',
    appId: '1:974045621368:android:2cfe0bf8d48e4c2b23d18d',
    messagingSenderId: '974045621368',
    projectId: 'flavr-4e17f',
    storageBucket: 'flavr-4e17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdytI4DXFOF5-WF8SEnSwamjs2O2fWCuM',
    appId: '1:974045621368:ios:240f64604e4ca0ad23d18d',
    messagingSenderId: '974045621368',
    projectId: 'flavr-4e17f',
    storageBucket: 'flavr-4e17f.firebasestorage.app',
    iosBundleId: 'com.example.flavr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdytI4DXFOF5-WF8SEnSwamjs2O2fWCuM',
    appId: '1:974045621368:ios:240f64604e4ca0ad23d18d',
    messagingSenderId: '974045621368',
    projectId: 'flavr-4e17f',
    storageBucket: 'flavr-4e17f.firebasestorage.app',
    iosBundleId: 'com.example.flavr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsM7qeT1vdZrThHozZpI5Faq1ivj-jKPg',
    appId: '1:974045621368:web:bced2568856e8f7323d18d',
    messagingSenderId: '974045621368',
    projectId: 'flavr-4e17f',
    authDomain: 'flavr-4e17f.firebaseapp.com',
    storageBucket: 'flavr-4e17f.firebasestorage.app',
    measurementId: 'G-H8718CVKNR',
  );
}
